// RENAME TO "gaballoc_ext.h"

#ifndef LIBK_GABALLOC_EXT_H
#define LIBK_GABALLOC_EXT_H 1

// Includes for defines

// Defines
#define GABALLOC_PAGE_SIZE ...
#define GABALLOC_ALLOC     ...
#define GABALLOC_FREE      ...
#define GABALLOC_MEMCPY    ...
#define GABALLOC_LOCK      ...
#define GABALLOC_UNLOCK    ...

#endif
